### PR TITLE
FIFO and LIFO strategies

### LINKED ISSUE #11: An option for choosing between LIFO and FIFO ordering
Tokio and Rayon need an option for fair scheduling (processing elements in FIFO order rather than LIFO). While we do support FIFO ordering, our performance is not as good as it could be...

Here's what we've learned over time so far:

* `crossbeam-deque` was initially designed as a LIFO data structure (`Deque::push()` and `Deque::pop()` work with one end, while `Stealer::steal()` works with the other end). Later on, we've added support for FIFO ordering (fair scheduling) through the `Deque::steal()` method. That means our deque now supports both FIFO and LIFO processing at the same time.

* A minor observation: the method `Deque::stealer()` is not that useful. I've searched for all uses of `crossbeam-deque` and it seems most users simply do `let d = Deque::new(); let s = d.stealer()` anyway. The old constructor that returns `(Worker<T>, Stealer<T>)` was serving us just fine.

* There have been multiple requests for *steal-half* operation (i.e. *batched steal*). Unfortunately, Chase-Lev deques cannot implement it particularly efficiently, but we can still gain something from batching. By batching multiple steal operations together, we can execute `epoch::pin()` only once rather within each call to `steal()`. This should give us some performance wins.

* `CircBuf` by @jeehoonkang is faster than `crossbeam-deque` because it doesn't attempt to support the `Deque::pop()` operation at all - i.e. it is a FIFO-only data structure. Moreover, the lack of `Deque::pop()` allows it to implement a very efficient batched steal operation. @carllerche has expressed interest in using it in Tokio.

I'd like to propose the following:

1. Let's merge `crossbeam-deque` and `CircBuf` into a single data structure, but differentiate between the underlying implementations at runtime ("flavors"). The same idea is used in `std::sync::mpsc` and `crossbeam-channel`, where we have two completely different implementations for bounded and unbounded channels but behind the same interface. Java's `ForkJoinPool` supports LIFO and FIFO very similarly (see [here](https://github.com/netroby/jdk9-dev/blob/master/jdk/src/java.base/share/classes/java/util/concurrent/ForkJoinPool.java#L2191)).

2. Let's tweak the interface a little bit for simplicity.

3. Let's add support for batched stealing.

Finally, here's the interface I'm proposing:

```rust
// `Worker::push()`   - bottom
// `Worker::pop()`    - top
// `Stealer::steal()` - top
fn fifo() -> (Worker<T>, Stealer<T>);

// `Worker::push()`   - bottom
// `Worker::pop()`    - bottom
// `Stealer::steal(). - top
fn lifo() -> (Worker<T>, Stealer<T>);

// Pushes and pops elements.
struct Worker<T>;

// Steals an element.
struct Stealer<T>;

impl<T> Worker<T> {
    // Pushes an element.
    fn push(&self, value: T);

    // Pops an element.
    fn pop(&self) -> Option<T>;

    fn is_empty(&self) -> bool;
    fn len(&self) -> usize;
}

impl<T> Stealer<T> {
    // Steals an element.
    fn steal(&self) -> Steal<T>;

    // Steals a batch of elements.
    fn steal_batch(&self) -> Steal<Batch<T>>;

    fn is_empty(&self) -> bool;
    fn len(&self) -> usize;
}

enum Steal<T> {
    // The queue was empty.
    Empty,

    // Some data was stolen.
    Data(T),

    // The operation should be retried.
    Retry,
}

// A batch of elements.
//
// Internally, this should probably be just a wrapper around
// `SmallVec::<[T; 16]>::IntoIter`, or something similar.
struct Batch<T>;

impl<T> Iterator for Batch<T> {
    type Item = T;
}
```

The advantages of this design are:

* By choosing LIFO or FIFO strategy at construction (functions `lifo()` and `fifo()`), we can internally use the most optimal implementation (Chase-Lev vs `CircBuf`) for methods `push`, `pop`, `steal`, and `steal_batch`.

* The interface is simple. One can easily choose the appropriate scheduling strategy (FIFO or LIFO) at runtime - we have a single `Worker` and `Stealer` type for both. This will be quite handy in Rayon.

What do you think?

cc @carllerche @jeehoonkang

### PR DESCRIPTION
**Pull request by ghost**
This PR adds two different ordering strategies to the deque: FIFO and LIFO. The strategy is chosen at construction time. There are two deque constructors:

```rust
fn fifo<T>() -> (Worker<T>, Stealer<T>);
fn lifo<T>() -> (Worker<T>, Stealer<T>);
```

FIFO is intended to be used by Tokio and LIFO is for Rayon. The FIFO variant doesn't execute any fences.

I've tried running benchmarks on Rayon's test suite and didn't find any significant differences between this PR and the current master branch.

The LIFO variant is the same as our current Chase-Lev implementation, while FIFO is slightly tweaked `CircBuf`. I've fixed a few bugs in `CircBuf`, cleaned up the code, and conservatively added a bit stronger memory orderings where I found them dubious. This time correctness is the primary concern, but we can revisit those orderings later to squeeze out more performance.

In a future PR we can also add methods for batched stealing (*steal half*), as explained in #11.

Another thing we should consider adding later is workers that can be shared among multiple threads. In addition to thread-local deques, schedulers usually also have a special global deque, where tasks without an associated worker thread go into (`rayon::spawn` pushes tasks into the global deque). Rayon currently uses `Mutex<Worker<T>>` and `Stealer<T>` for the global deque. The mutex around `Worker<T>` is unfortunate so we should ideally add a variant of deque that supports *push* and *pop* from multiple threads without mutexes. Such a deque would probably be implemented as a Treiber stack when using LIFO strategy and as a Michael-Scott queue when using FIFO strategy.

Closes #11 
cc @carllerche

### CODE REVIEW

**Comment by ghost** [comment]
What do you think, @jeehoonkang? :)

I don't think this PR needs thorough review - it's just refactoring + `CircBuf` with slightly stronger orderings (for now).

**Comment by ghost** [comment]
As suggested in https://github.com/tokio-rs/tokio/issues/426, I've moved some worker-specific data from `Inner` into `Worker`. This means buffer pointer, buffer capacity, and the back index get inlined directly into `worker::Entry`.

Comparison between the Tokio master branch and my local branch that uses this PR:

```
 name                    before ns/iter  after ns/iter  diff ns/iter  diff %  speedup
 threadpool::spawn_many  4,659,536       4,199,011          -460,525  -9.88%   x 1.11
 threadpool::yield_many  11,949,901      12,170,009          220,108   1.84%   x 0.98
```

The `yield_many` benchmark is slightly slower now - my guess is that's because the steal operation is now a bit slower in case the deque is empty (because we have to load the stamp inside the buffer instead of loading the back index). But I believe this is overall for the better.

I'm also hopeful that batched stealing will give us further performance wins.

(Just a reminder: this is blocked on Tokio upgrading to Rust 1.25).

**Comment by carllerche** [comment]
I merged https://github.com/tokio-rs/tokio/pull/465, so Tokio should be on 1.25

**Comment by ghost** [comment]
Ok, let's merge this.

@jeehoonkang I'm going to skip the review - if you have any comments on this PR, let me know anytime. :)

**Pull request merged**
