### PR TITLE
Support Rust 1.20.0

### PR DESCRIPTION
**Pull request by ghost**
I just picked the first Rust version with `pub(restricted)` and changed `a.max(b)` to `cmp::max(a, b)` to make the code compile at that version.

Closes #3.

### CODE REVIEW

**Comment by BurntSushi** [comment]
It looks like `crossbeam-deque 0.3.0` contains the `a.max(b)` code, which means it does not compile on Rust 1.20.

**Comment by ghost** [comment]
@BurntSushi Well, this PR changes the `a.max(b)` code to `cmp::max(a, b)`. Am I missing something? :)

**Comment by BurntSushi** [comment]
@stjepang What I meant is that there is already a release of this crate that requires a newer version of Rust to compile. If we want to support older versions, then we should just merge this and fix the problem.

**Review by jeehoonkang — APPROVED** [review]

**Comment by jeehoonkang** [comment]
Thanks!  I'm merging it right now.

**Pull request merged**
